### ISSUE TITLE
Adding miner logic

### ISSUE THREAD

**Issue by bobdubois** [jcrowthe/ace_of_spades#10]
How hard would it be to add some lotus-miner logic to this?
I've been looking for the boost graphql query to incorporate logic around the amount of sectors actively in the sealing pipeline. With that ace-of-spades could get a parameter to only pull in new deals if the miner is below a certain threshold.
Yet, I couldn't work out the query...

**Comment by jcrowthe** [comment]
Hey, this functionality already exists in Ace, but was restricted to just snap sectors. I've updated the parameter to take into account both snap and regular sectors now, as determined by the count of PC1 sectors in flight. If below that count, new Spade deals will be requested. If above that count, new deals will not be requested.

Note that there are several limiting factors you can play with, found in the docs. Use them in combination with each other to provide the protections you need.
